#pragma once

#define IDC_TAB_GLOBAL						4000

//ctrl id
#define IDC_BTN_SYS_CLOSE                   60001
#define IDC_BTN_TEST						60002
#define IDC_BTN_SYS_MIN						60003
#define IDC_BTN_SYS_MORE                    60000


#define IDC_NETCONFIG_NETWORK_DEVICE_LISTVIEW   2001
#define IDL_PROCESS_LIST                        2002
#define IDL_TCPCONNECTION_LIST                  2003
#define IDL_UDPCONNECTION_LIST                  2004
#define IDL_ROUTE_LIST							2005

#define IDC_BTN_PROCESS_RELOAD					2006
#define IDC_BTN_TCP_STATUS_RELOAD				2007
#define IDC_BTN_UDP_STATUS_RELOAD				2008
#define IDC_BTN_ROUTE_STATUS_RELOAD				2009
#define IDC_TEXT_PROCESS_COUNT					2010
#define IDC_TEXT_TCP_CONNECTION_COUNT			2011
#define IDC_TEXT_UDP_CONNECTION_COUNT			2012
#define IDC_TEXT_ROUTE_CONNECTION_COUNT			2013

// »Ìº˛…Ë÷√
#define IDCK_CONFIG_AUTORUN						2014
#define IDC_BTN_CONFIG_SUBMIT					2015
#define IDC_BTN_CONFIG_CANCEL					2016
#define IDC_CHKBTN_AUTORUN_HIDE					2017
#define IDC_CHKBTN_WINDOW_ON_TOP				2018
#define IDC_RADIO_BTN_AUTO_UPDATE				2019
#define IDC_RADIO_BTN_CUSTOM_UPDATE				2020
#define IDC_RADIO_BTN_LANGUAGE_CHS				2021
#define IDC_RADIO_BTN_LANGUAGE_EN				2022
#define IDC_REALWND_NET_STATUS					2023
#define IDC_CHECK_BTK_AUTO_FLUSH_INFO			2024
#define IDC_REALWND_NET_FLOW					2025

#define IDC_BUTTON_CONFIG_SPEED_BG_COLOR		2026
#define IDC_BUTTON_CONFIG_SPEED_UP_COLOR		2027
#define IDC_BUTTON_CONFIG_SPEED_DOWN_COLOR		2028
#define IDC_BUTTON_CONFIG_FLOW_BG_COLOR			2029
#define IDC_BUTTON_CONFIG_FLOW_UP_COLOR			2030
#define IDC_BUTTON_CONFIG_FLOW_DOWN_COLOR		2031
#define IDC_BUTTON_CONFIG_SPEED_GRID_LINE		2032
#define IDC_BUTTON_CONFIG_FLOW_GRID_LINE		2033

//string id
#define IDS_APP_FONT						1

